# Question 1
# Ans

In [3]:
import numpy as np

In [4]:
np.arange(2,51,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [6]:
x = np.arange(2,51,3)

In [7]:
x

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Question 2
# Ans

In [18]:
lst1 = []
lst2 = []
for i in range(5):
    x = int(input("Enter the element for list 1 "))
    lst1.append(x)
    
for i in range(5):
    y = int(input("Enter the element for list 2 "))
    lst1.append(y)
A = np.array(lst1)
B = np.array(lst2)
print("The Concatenated Array is ",np.concatenate((A,B),axis = 0 ))
print("The Sorted Array is ",np.sort(np.concatenate((A,B),axis = 0 )))

Enter the element for list 1 1
Enter the element for list 1 23
Enter the element for list 1 43
Enter the element for list 1 45
Enter the element for list 1 56
Enter the element for list 2 67
Enter the element for list 2 54
Enter the element for list 2 66
Enter the element for list 2 89
Enter the element for list 2 78
The Concatenated Array is  [ 1. 23. 43. 45. 56. 67. 54. 66. 89. 78.]
The Sorted Array is  [ 1. 23. 43. 45. 54. 56. 66. 67. 78. 89.]


# Question 3
# Ans

In [42]:
nl = np.arange(15).reshape((3,5))
print(nl)
print(np.ndim(nl))
print(nl.size)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2
15


# Question 4
# Ans

In [78]:
k = np.array([np.arange(1,10)]) # here np.array creates nd array it stored to variable k
y = np.expand_dims(k,axis=1)   #here the expanded dimension of array is stored to y

y.shape #here we shows the size of the array looks how it changes if changes the value of x
y

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [77]:
k = np.array([np.arange(1,10)])
y = np.expand_dims(k,axis=2)

y.shape
y

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]])

# Question 5
# Ans

In [101]:
A = np.arange(4).reshape(2,2)
B = np.arange(4,8).reshape(2,2)
print("The Horizontal Stacked Array")
print(np.hstack((A,B)))
print("The Vertical Stacked Array")
print(np.vstack((A,B)))

The Horizontal Stacked Array
[[0 1 4 5]
 [2 3 6 7]]
The Vertical Stacked Array
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


# Question 6
# Ans

In [119]:
n = int(input("How Many Number you Want to Enter "))
lst = []
for i in range(n):
    x = int(input("Enter the Numbers "))
    lst.append(x)
unique_list = []
nx = np.array(lst)
print(np.unique(nx))

How Many Number you Want to Enter 5
Enter the Numbers 11
Enter the Numbers 11
Enter the Numbers 12
Enter the Numbers 133
Enter the Numbers 12
[ 11  12 133]
